### PR TITLE
Slide toggle

### PR DESCRIPTION
**Pull request by JustinO1055**

### CODE REVIEW

**Review by MitchLehrer — APPROVED** [review]

**Comment by Sam-Dietrich** [comment]
Couple conflicts with the base, @JustinO1055 can you resolve then notify the team?

**Comment by Sam-Dietrich** [comment]
Hey Guys, no changes since I escalated this last month. Happy to help resolve conflicts if that'd speed things along but let's try to get this in by EOW!

**Comment by Patrick-Ullrich** [comment]
Hey Guys, this is a blocker for us. Can someone fix those conflicts and lets get this merged.

Thanks!

**Comment by ryan4664** [comment]
Dislike the use of `any` but let's get this merged!

**Comment by Sam-Dietrich** [comment]
Hey everyone, the last thing I want to do is to ask people to work over Christmas. But so help me God I will if we don't get this handled soon!

**Comment by Nickknack** [comment]
@Sam-Dietrich @ryan4664 @Patrick-Ullrich are you harassing my boys?

**Comment by ryan4664** [comment]
@Nickknack just trying to get this merged, haven't worked in months because of this blocker

**Review by ryan4664 — APPROVED** [review]

**Comment by Patrick-Ullrich** [comment]
I think it's safe to say that this project has been abandoned. Can't fault the maintainer, OS is a thankless job - but it be good to know if there are any alternatives available.

**Comment by Sam-Dietrich** [comment]
My wife is threatening to leave me unless this gets merged

**Comment by ryan4664** [comment]
All good on this actually, just heard from @Sam-Dietrich and his wife left him. No rush on this now, thanks.

**Comment by streibeb** [comment]
Wow that was a quick divorce. Sorry to hear that @Sam-Dietrich.

**Comment by Jimeh87** [comment]
@Jucojo @Nickknack @ghudner let's get our new hires on this! It might be too late for Sam's marriage, but maybe, just maybe, we can save Sam's second marriage.

**Comment by Nickknack** [comment]
@Jimeh87 This will cut into our progress in dipping into the game space. Two-shot golf will need to be put on the back-burner. I know we hate hard-dates but I feel like if we're aligned we could get this in before Sam's next wedding.

**Comment by ryan4664** [comment]
We decided to go a different route, thank you everyone for your continued efforts

**Pull request closed without merging**
